name: soto_project
description: Flutter SOTO project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: 3.0.0
  shared_preferences: ^2.0.1
  geolocator: ^8.0.3
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.0.3
  onesignal_flutter: ^3.2.8
  flutter_screenutil: ^5.2.0
  mapbox_gl: ^0.15.0
  flutter_conditional_rendering: ^2.0.0
  file_picker: ^4.4.0
  share_plus: ^3.0.4
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  wakelock: ^0.6.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/marker.png
    - assets/car.png
    - assets/menu/icon1.svg
    - assets/menu/icon2.svg
    - assets/menu/icon3.svg
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
